'Online Multi-choice Exam Web App':
  'TODO':
    - 'fresh'
    - 'confirmed'
  'In Progress':
    - 'doing'
  'Bugfix':
    - 'bug'
  'Review + Testing':
    - 'reviewing'
  'Mergeable':
    - 'pending merge'
  'Backlog':
    - 'maybe later'
  'Sprint1':
    - 'sprint 1'
  'Sprint 2':
    - 'sprint 2'
  'Sprint 3':
    - 'sprint 3'
