version: "3"
services:
  pg-mana:
    image: postgres:latest
    container_name: pg-mana
    ports:
      - "3306:3306"

    volumes:
      - ./docker_data/db-docker:/var/lib/postgresql/data
      - ./docker_data/db-config:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DBSPACE}

  api:
    build: ./backend/src
    depends_on:
      - pg-mana
    volumes:
      - ./backend/src/:/app/
      - ./backend/src/wait:/wait
    ports:
      - "${UVICORN_PORT}:${UVICORN_PORT}"
    command: sh -c  /start-reload.sh
    environment:
      - DATABASE_ECHO=1
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${UVICORN_PORT}
