version: "3"
services:
  mysql-mana:
    image: mysql:latest
    container_name: mysql-mana
    ports:
      - "3306:3306"

    volumes:
      - ./docker_data/db-docker:/var/lib/mysql
      - ./docker_data/db-config:/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DBSPACE}
