version: "3"
services:
  pg-mana:
    image: postgres:latest
    container_name: pg-mana
    ports:
      - "3306:3306"

    volumes:
      - ./docker_data/db-docker:/var/lib/postgresql/data
      - ./docker_data/db-config:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DBSPACE}
