version: "3"
services:
  pg-mana:
    image: postgres:latest
    container_name: pg-mana
    ports:
      - "3306:3306"

    volumes:
      - ./docker_data/db-docker:/var/lib/postgresql/data
      - ./docker_data/db-config:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DBSPACE}
  api:
    build: ./backend/src
    volumes:
      - ./backend/src/:/app/
      - ./backend/src/wait:/wait
    ports:
      - "8080:8080"
    command: sh -c  /start-reload.sh
    environment:
      # - WAIT_HOSTS=pg-mana:3306
      - DATABASE_ECHO=1
      - DATABASE_URL=${DATABASE_URL}
      - PORT=8080
