name: Add Label Milestone Event

on:
  issues:
    types: [ milestoned ]

jobs:
  triage:
    name: Adding label to milestoned issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            console.log(context)
            console.log('1',context.github)
            console.log('2',context.payload)
            console.log('3',context.payload.event)
