name: ProjectCard Auto Labels

on:
  project_card:
    types: [ created, moved ]

jobs:
  projectcardautolabel_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run ProjectCard AutoLabel
        id: runprojectcardautolabel
        uses: Matticusau/projectcard-autolabel@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          autolabel-config: '
          [{"column":"TODO", "add_labels":["fresh", "confirmed"], "remove_labels":["doing","bug", "reviewing", "wont fix"]},
          {"column":"In Progress", "add_labels":["doing"], "remove_labels":["fresh", "confirmed","bug", "reviewing", "wont fix"]},
          {"column":"Bugfix", "add_labels":["bug"], "remove_labels":["fresh", "confirmed","doing","reviewing", "wont fix"]},
          {"column":"Review + Testing", "add_labels":["reviewing"], "remove_labels":["fresh", "confirmed","doing","bug","wont fix"]},
          {"column":"Done", "add_labels":[], "remove_labels":["fresh", "confirmed","doing","bug", "reviewing", "wont fix"]},
          {"column":"Backlog", "add_labels":["wont fix"], "remove_labels":["fresh", "confirmed","doing","bug", "reviewing"]}]
          '
